site_name: JusPay Express Checkout Docs
pages:
    - ['index.md', 'Getting Started', 'Introduction']
    - ['account.md', 'Getting Started', 'Setup JusPay Account']
    - ['order.md', 'Integration', 'Order creation']
    - ['iframe.md', 'Integration', 'Pay using iFrame']
theme: readthedocs
